version: 2

jobs:
  build:
    docker:
      - image: "circleci/node:10.15.0-browsers-legacy@sha256:8c1db0de8629fc48c9aa9165a4697f3e485093ad151660ce3fde954a8b084791"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage
